[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
klyra-secrets = "0.5.2"
klyra-service = { version = "0.5.2", features = ["bot-serenity"] }
