version: "3"
services:
  app:
    build: .
    ports:
      - "8001:8001"
      - "8000:8000"
    volumes:
      - ./api/users.toml:/config/users.toml
      - /tmp/klyra/crates:/var/lib/klyra/crates
    environment:
      - klyra_USERS_TOML=/config/users.toml
      - klyra_ADMIN_SECRET=admin-pass
