[package]
name = "klyra-warp"
version = "0.49.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a warp webserver on klyra"
repository = "https://github.com/klyra-hq/klyra"
keywords = ["klyra-service", "warp"]

[workspace]

[dependencies]
warp = "0.3.3"
klyra-runtime = { path = "../../runtime", version = "0.49.0", default-features = false }
