[package]
name = "klyra-warp"
version = "0.34.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a warp webserver on klyra"
keywords = ["klyra-service", "warp"]

[workspace]

[dependencies]
warp = { version = "0.3.3" }
klyra-runtime = { path = "../../runtime", version = "0.34.0", default-features = false }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
