[package]
name = "klyra-service"
version = "0.21.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Service traits and macros to deploy on the klyra platform (https://www.klyra.rs/)"
homepage = "https://www.klyra.rs"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
cargo_metadata = { workspace = true, optional = true }
crossbeam-channel = { workspace = true, optional = true }
os_pipe = { version = "1.1.4", optional = true }
serde = { workspace = true, features = ["derive"] }
strfmt = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["process"], optional = true }
toml = { workspace = true, optional = true  }
tracing = { workspace = true, optional = true }

[dependencies.klyra-common]
workspace = true
features = ["service"]

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = []

builder = ["cargo_metadata", "crossbeam-channel", "os_pipe", "tokio", "toml", "tracing"]
