[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
poem = "1.3.35"
serde = "1.0"
klyra-secrets = "0.5.2"
klyra-service = { version = "0.5.2", features = ["web-poem"] }
klyra-shared-db = { version = "0.5.2", features = ["postgres"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres"] }
