[advisories]
ignore = [
  # Advisory about a vulnerability in rsa, which we don't use, but it is pulled in via sqlx due
  # to a bug in cargo. See https://github.com/klyra-hq/klyra/pull/1475 for context.
  "RUSTSEC-2023-0071"
]
