[package]
name = "klyra-static-folder"
version = "0.8.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to get a static folder at runtime on klyra"
keywords = ["klyra-service", "static-folder"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
klyra-service = { path = "../../service", version = "0.8.0", default-features = false }

[dev-dependencies]
tempdir = "0.3.7"
tokio = { version = "1.19.2", features = ["macros"] }
