[package]
name = "klyra-tower"
version = "0.55.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a tower webserver on klyra"
repository = "https://github.com/klyra-hq/klyra"
keywords = ["klyra-service", "tower"]

[workspace]

[dependencies]
hyper = { version = "0.14.23", features = ["server", "tcp", "http1"] }
klyra-runtime = { path = "../../runtime", version = "0.55.0", default-features = false }
tower = { version = "0.4.13", features = ["make"] }
