[package]
name = "klyra-common-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
hyper = { workspace = true }
klyra-common = { workspace = true }
tower = { workspace = true }
cargo-klyra = { path = "../cargo-klyra" }
portpicker = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
