[package]
name = "klyra-metadata"
version = "0.39.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to get Klyra service information"
keywords = ["klyra-service", "metadata"]

[dependencies]
async-trait = "0.1.56"
klyra-service = { path = "../../service", version = "0.39.0" }
